Add support for embedded types
mobxjs/serializr pull request #140
Opened 2020-08-26 21:35 UTC by danfma

These changes will allow support for embedded types or maybe more powerful custom serializers.
It allows the user to change the outputted object during the serialization/deserialization.

- A new custom type was created too (embedded), which embed the object data into the parent resulting JSON (and vice-versa).

2020-08-26 21:41 UTC, danfma commented
@NaridaL @mweststrate  Should I update the README manually or did I miss any step? Locally, it looks to be working (build and tests). :)

2020-12-16 23:32 UTC, NaridaL requested changes
You need to run `yarn build-docs` to rebuild the README.

2020-12-16 23:32 UTC, NaridaL commented on src/types/embedded.ts
> +    return custom(
The other built-in types don't use custom, rather they build a `PropSchema` manually. Unless there is a specific reason, we should do the same here.

2020-12-16 23:32 UTC, NaridaL commented on src/types/embedded.ts
> +export default function embedded<T>(type: ClazzOrModelSchema<T>) {
Other built-in types all accept an ` additionalArgs?: AdditionalPropArgs` argument. We should do the same here.

For this type to be flexible, we probably need a "prefix" option.

2020-12-16 23:32 UTC, NaridaL commented on src/types/embedded.ts
> +            }
Is this necessary? It doesn't seem to do anything.

2020-12-16 23:32 UTC, NaridaL commented on test/typescript/ts.ts
> +test("embedded(type)", (t) => {
The other typescript tests all use decorators. Can we move these to simple.js?

2020-12-16 23:32 UTC, NaridaL commented on src/types/embedded.ts
> + */
Please add an example of the usage here. See the other built in types for how to format it so that it shows up properly in the README.

2021-01-02 01:27 UTC, pyrogenic commented
This is an interesting idea. I think `inline` might suggest its purpose more readily? As a decorator it would then read `@serialize(inline(ClassName))`.

I do see a lot of potential for property collisions or otherwise acting on a JSON element more than once, which gives me pause.

Interestingly, in my own work, I could use the opposite: I have to deal with wiretypes full of totally unnecessary object nesting.

2025-04-04 13:08 UTC, closed without merging